// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CryptoUIClient is the client API for CryptoUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CryptoUIClient interface {
	// ListEngineSpecs returns a list of Cryptography Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (CryptoUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type cryptoUIClient struct {
	cc grpc.ClientConnInterface
}

func NewCryptoUIClient(cc grpc.ClientConnInterface) CryptoUIClient {
	return &cryptoUIClient{cc}
}

func (c *cryptoUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (CryptoUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &CryptoUI_ServiceDesc.Streams[0], "/v1.CryptoUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &cryptoUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CryptoUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type cryptoUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *cryptoUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cryptoUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.CryptoUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CryptoUIServer is the server API for CryptoUI service.
// All implementations must embed UnimplementedCryptoUIServer
// for forward compatibility
type CryptoUIServer interface {
	// ListEngineSpecs returns a list of Cryptography Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, CryptoUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedCryptoUIServer()
}

// UnimplementedCryptoUIServer must be embedded to have forward compatible implementations.
type UnimplementedCryptoUIServer struct {
}

func (UnimplementedCryptoUIServer) ListEngineSpecs(*ListEngineSpecsRequest, CryptoUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedCryptoUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedCryptoUIServer) mustEmbedUnimplementedCryptoUIServer() {}

// UnsafeCryptoUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CryptoUIServer will
// result in compilation errors.
type UnsafeCryptoUIServer interface {
	mustEmbedUnimplementedCryptoUIServer()
}

func RegisterCryptoUIServer(s grpc.ServiceRegistrar, srv CryptoUIServer) {
	s.RegisterService(&CryptoUI_ServiceDesc, srv)
}

func _CryptoUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CryptoUIServer).ListEngineSpecs(m, &cryptoUIListEngineSpecsServer{stream})
}

type CryptoUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type cryptoUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *cryptoUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _CryptoUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.CryptoUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CryptoUI_ServiceDesc is the grpc.ServiceDesc for CryptoUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CryptoUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.CryptoUI",
	HandlerType: (*CryptoUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _CryptoUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _CryptoUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "crypto-ui.proto",
}
